# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31950d9a8195eccc25dfcff6dfa4104ac5c085fe4f390f046870ba1213746185cfef78071eb54a5d0e4c93143e7abc48cc02cf066305ca11331769213c27b87e

test:
  secret_key_base: 91bac2bcfffcd5f4e08a4c04c8de386d213756d6ca87efe27af70438190ddf4c8d545c86961fca3bf45cc64310af701e5e184d6931e55c173850ffadc409cb82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
